### ISSUE TITLE
Access and modify physics properties

### ISSUE THREAD

**Issue by Prasanna-kumar-Patra** [splinetool/r3f-spline#12]
Need feature to Access and modify physics properties from spline
Need support for spline physics to render and API

**Comment by marcofugaro** [comment]
Physics are not supported in r3f-spline. Use [react-spline](https://github.com/splinetool/react-spline) if you want physics.

**Comment by Prasanna-kumar-Patra** [comment]
Thanks for the quick reply
Any standalone example will be appreciable 
to enable/disable and get/set physics properties
