### ISSUE TITLE
Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by vlad-terin** [splinetool/r3f-spline#4]
![pic-selected-220812-2039-03](https://user-images.githubusercontent.com/5722749/184463724-946344d2-80a5-427e-80d0-1ce000fb6dfa.png)

New to next js and spline, could someone help with this error:

TypeError
Cannot set properties of undefined (setting 'value')

https://codesandbox.io/s/ftyxeq?file=/src/Scene.js

**Comment by PeterTF656** [comment]
I think we are facing a similar issue. Watching...

**Comment by marcofugaro** [comment]
Should be fixed in version `0.9.102` of `@splinetool/loader`
