### ISSUE TITLE
Exported to R3F Gives Error: Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by PeterTF656** [splinetool/r3f-spline#5]
https://codesandbox.io/s/vkx82s?file=/src/Scene.js

This scene works fine when exported in React, but in the case of R3F, it gave me this error:

![errpr-r3f](https://user-images.githubusercontent.com/71594839/185442631-cb35fb5f-02cf-4d56-b50d-857745197a7c.jpg)

**Comment by marcofugaro** [comment]
Should be fixed in version `0.9.102` of `@splinetool/loader`
