### ISSUE TITLE
SplineLoader using deprecated three.js classes

### ISSUE THREAD

**Issue by seinaas** [splinetool/r3f-spline#8]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/38442884/197810548-1837c479-246d-4d3b-80c1-245083d08a2a.png">

I'm getting warnings from THREE for using deprecated geometry classes. It looks like the issue is coming from the SplineLoader class.

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/loader` version `0.9.132`
